name: playwright
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Use variables
        run: |
          echo "sendgrid api key : $NEXT_PUBLIC_SENDGRID_API_KEY"
          echo "sendgrid email : $NEXT_PUBLIC_SENDGRID_EMAIL"
          echo "sanity studio api version : $NEXT_PUBLIC_SANITY_STUDIO_API_VERSION"
          echo "sanity studio dataset : $NEXT_PUBLIC_SANITY_STUDIO_DATASET"
          echo "sanity studio project id : $NEXT_PUBLIC_SANITY_STUDIO_PROJECT_ID"
          echo "sanity studio title : $NEXT_PUBLIC_SANITY_STUDIO_TITLE"
        env:
          NEXT_PUBLIC_SENDGRID_API_KEY: ${{ vars.NEXT_PUBLIC_SENDGRID_API_KEY }}
          NEXT_PUBLIC_SENDGRID_EMAIL: ${{ vars.NEXT_PUBLIC_SENDGRID_EMAIL }}
          SANITY_STUDIO_API_VERSION: ${{ vars.NEXT_PUBLIC_SANITY_STUDIO_API_VERSION }}
          SANITY_STUDIO_DATASET: ${{ vars.NEXT_PUBLIC_SANITY_STUDIO_DATASET }}
          SANITY_STUDIO_PROJECT_ID: ${{ vars.NEXT_PUBLIC_SANITY_STUDIO_PROJECT_ID }}
          SANITY_STUDIO_TITLE: ${{ vars.NEXT_PUBLIC_SANITY_STUDIO_TITLE }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30
